import { siteConfig } from "@/lib/siteConfig";

function Section({
  number,
  title,
  children,
}: {
  number: number;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mt-8">
      <h2 className="text-xl font-semibold">
        {number}. {title}
      </h2>
      <div className="mt-2 space-y-3 text-sm leading-relaxed text-neutral">
        {children}
      </div>
    </section>
  );
}

export default function Terms() {
  return (
    <div className="mx-auto max-w-2xl px-6 py-16">
      <h1 className="text-3xl font-semibold">Terms &amp; Conditions</h1>
      <p className="mt-2 text-sm text-neutral">
        Last updated: {siteConfig.lastUpdated}
      </p>

      <Section number={1} title="Acceptance of Terms">
        <p>
          By creating an account or using {siteConfig.appName}, you agree to
          these terms. If you don&apos;t agree, please don&apos;t use the app.
        </p>
      </Section>

      <Section number={2} title="Description of Service">
        <p>
          {siteConfig.appName} is a personal budgeting app. It helps you track
          income and expenses and turns them into a daily safe-to-spend figure,
          with AI-written reports about your own spending data. It&apos;s
          provided for informational purposes only and is not financial,
          investment, tax, or legal advice — decisions you make based on it are
          your own.
        </p>
      </Section>

      <Section number={3} title="Accounts & Google Sign-In">
        <p>
          You can sign in with Google or with an email and password. Signing in
          lets your budget sync across devices and survive a reinstall.
          You&apos;re responsible for the accuracy of what you enter and for
          keeping your credentials secure. You must be legally able to enter
          into these terms to create an account.
        </p>
      </Section>

      <Section number={4} title="Acceptable Use">
        <p>
          Don&apos;t use {siteConfig.appName} for anything unlawful, don&apos;t
          try to reverse-engineer or interfere with the app or its backend, and
          don&apos;t abuse the AI report feature — for example, to generate
          content unrelated to your own budgeting data.
        </p>
      </Section>

      <Section number={5} title="AI Reports">
        <p>
          Weekly and month-end reports, and any budget explanations, are
          generated by an AI model from your own financial summary. They are
          not professional financial advice — always use your own judgment
          before acting on them, and verify anything important yourself.
        </p>
      </Section>

      <Section number={6} title="Your Content">
        <p>
          The income, expenses, goals, and any bank statements you enter or
          import remain yours. We use them only to run the app&apos;s features
          for you, as described in the{" "}
          <a className="text-brand underline" href="/privacy">
            Privacy Policy
          </a>
          .
        </p>
      </Section>

      <Section number={7} title="Third-Party Services">
        <p>
          The app relies on Firebase (Authentication and Cloud Firestore) and
          Groq (AI report generation) to work. Their handling of your data is
          described in the{" "}
          <a className="text-brand underline" href="/privacy">
            Privacy Policy
          </a>
          . Some features may require a paid subscription purchased through
          Google Play; pricing, renewal, cancellation, and refunds for any such
          subscription are handled by Google Play under its own policies.
        </p>
      </Section>

      <Section number={8} title="Termination">
        <p>
          You may stop using the app or delete your account at any time, from
          within the app or from{" "}
          <a className="text-brand underline" href="/delete-account">
            this website
          </a>
          . We may suspend or terminate accounts that violate these terms.
        </p>
      </Section>

      <Section number={9} title="Disclaimer of Warranties">
        <p>
          The app, including bank-statement parsing and AI-generated reports,
          is provided &quot;as is.&quot; We don&apos;t guarantee that figures,
          categorizations, or AI reports are complete or error-free.
        </p>
      </Section>

      <Section number={10} title="Limitation of Liability">
        <p>
          To the fullest extent permitted by law, we are not liable for
          indirect, incidental, or consequential damages arising from your use
          of the app.
        </p>
      </Section>

      <Section number={11} title="Changes to These Terms">
        <p>
          If these terms change materially, we&apos;ll update the date above
          and, where required, notify you in the app.
        </p>
      </Section>

      <Section number={12} title="Governing Law">
        <p>These terms are governed by the laws of {siteConfig.jurisdiction}.</p>
      </Section>

      <Section number={13} title="Contact">
        <p>
          Questions about these terms:{" "}
          <a className="text-brand underline" href={`mailto:${siteConfig.contactEmail}`}>
            {siteConfig.contactEmail}
          </a>
        </p>
      </Section>
    </div>
  );
}
